### ISSUE TITLE
use next-mdx-remote instead of next-mdx-enhanced

### ISSUE THREAD

**Issue by Neobii** [VulcanJS/vulcan-next#86]
The author of `next-mdx-enhanced` suggests to now use [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote).  
[github readme notice](https://github.com/hashicorp/next-mdx-enhanced#nextjs--mdx-enhanced)

**Comment by Neobii** [comment]
Seems like this should work right off the bat with mdx right?

```
import Head from 'next/head';

<Head>
  <link rel="icon" href="/favicon_io/favicon.ico" />
  <meta name="description" content="Dishes the index."></meta>
  <title>Vulcan next</title>
</Head>

# Vulcan Next
```

Perhaps this is caused by this library and it will be fixed if we switch to the new one.

**Comment by eric-burel** [comment]
Will take a look, it may take some time because that's a complex lib, but yeah if it is recommended let's go with an update.

**Comment by eric-burel** [comment]
The fun thing is that technically using a `components` object reminds me a lot Vulcan Meteor component system: https://nextjs.org/blog/markdown

**Comment by eric-burel** [comment]
Release incoming in a few minutes \o/ Architecture is way cleaner like this.
